# Site settings
title: audioroger
#email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  An audiophile that codes.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://audioroger.github.io" # the base hostname & protocol for your site
twitter_username: audioroger
github_username:  audioroger

# Build settings
markdown: kramdown
